apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: miniodb-system
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: miniodb-system
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app.kubernetes.io/name: redis

---
# Redis Headless Service (用于StatefulSet)
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: miniodb-system
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: miniodb-system
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app.kubernetes.io/name: redis 