redis:
  addr: "localhost:6379"
  password: ""
  db: 0

minio:
  endpoint: "localhost:9000"
  access_key_id: "minioadmin"
  secret_access_key: "minioadmin"
  use_ssl: false
  bucket: "main-data"

server:
  grpc_port: ":50051"
  rest_port: ":8080"
  node_id: "node-1"

backup:
  enabled: false
  minio:
    endpoint: "localhost:9001"
    access_key_id: "backup_user"
    secret_access_key: "backup_password"
    use_ssl: false
    bucket: "olap-backup-bucket"

buffer:
  max_size: 1000
  flush_timeout: 30
  batch_size: 100

log:
  level: "info"
  format: "json"
  output: "stdout"
  file: ""

monitoring:
  enabled: true
  port: ":9090"
  path: "/metrics"
  prometheus: true

security:
  enable_tls: false
  cert_file: ""
  key_file: ""
  enable_auth: false
  auth_token: ""

# 新增认证配置
auth:
  enable_jwt: true
  jwt_secret: "your-super-secret-jwt-key-change-this-in-production"
  token_expiry: "24h"
  enable_api_key: true
  api_keys:
    - "api-key-1234567890abcdef"
    - "api-key-0987654321fedcba"
  skip_auth_paths:
    - "/health"
    - "/metrics"
    - "/v1/health"
  require_auth_paths:
    - "/v1/write"
    - "/v1/query"
    - "/v1/backup/trigger"
    - "/v1/recover"
  admin_roles:
    - "admin"
    - "superuser"
  user_roles:
    - "user"
    - "api" 