redis:
  addr: "localhost:6379"
  password: ""
  db: 0

minio:
  endpoint: "localhost:9000"
  access_key_id: "minioadmin"
  secret_access_key: "minioadmin"
  use_ssl: false
  bucket: "olap-data"

server:
  grpc_port: ":8080"
  rest_port: ":8081"
  node_id: "node-1"

backup:
  enabled: true
  interval: 3600  # 备份间隔（秒）
  minio:
    endpoint: "localhost:9000"
    access_key_id: "minioadmin"
    secret_access_key: "minioadmin"
    use_ssl: false
    bucket: "olap-backup"

buffer:
  max_size: 1000
  flush_timeout: 30
  batch_size: 100

log:
  level: "info"
  format: "json"
  output: "both"
  filename: "logs/miniodb.log"
  max_size: 100
  max_backups: 5
  max_age: 30
  compress: true

monitoring:
  enabled: true
  port: ":9090"
  path: "/metrics"
  prometheus: true

security:
  mode: "none"                    # "none" 或 "token"
  jwt_secret: ""                  # JWT密钥，留空自动生成
  valid_tokens: []                # 预设的有效token列表
  enable_tls: false              # 是否启用TLS
  cert_file: "certs/server.crt"  # 证书文件路径
  key_file: "certs/server.key"   # 私钥文件路径

# 新增认证配置
auth:
  enable_jwt: true
  jwt_secret: "your-super-secret-jwt-key-change-this-in-production"
  token_expiry: "24h"
  enable_api_key: true
  api_keys:
    - "api-key-1234567890abcdef"
    - "api-key-0987654321fedcba"
  skip_auth_paths:
    - "/health"
    - "/metrics"
    - "/v1/health"
  require_auth_paths:
    - "/v1/write"
    - "/v1/query"
    - "/v1/backup/trigger"
    - "/v1/recover"
  admin_roles:
    - "admin"
    - "superuser"
  user_roles:
    - "user"
    - "api" 