version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: miniodb-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1 --loglevel warning

  minio:
    image: minio/minio:RELEASE.2023-09-04T19-57-37Z
    container_name: miniodb-minio
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

volumes:
  redis-data:
  minio-data: 