// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: olap.proto

package olapv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OlapService_Write_FullMethodName                  = "/olap.v1.OlapService/Write"
	OlapService_Query_FullMethodName                  = "/olap.v1.OlapService/Query"
	OlapService_TriggerBackup_FullMethodName          = "/olap.v1.OlapService/TriggerBackup"
	OlapService_RecoverData_FullMethodName            = "/olap.v1.OlapService/RecoverData"
	OlapService_HealthCheck_FullMethodName            = "/olap.v1.OlapService/HealthCheck"
	OlapService_GetStats_FullMethodName               = "/olap.v1.OlapService/GetStats"
	OlapService_GetNodes_FullMethodName               = "/olap.v1.OlapService/GetNodes"
	OlapService_CreateTable_FullMethodName            = "/olap.v1.OlapService/CreateTable"
	OlapService_DropTable_FullMethodName              = "/olap.v1.OlapService/DropTable"
	OlapService_ListTables_FullMethodName             = "/olap.v1.OlapService/ListTables"
	OlapService_DescribeTable_FullMethodName          = "/olap.v1.OlapService/DescribeTable"
	OlapService_TriggerMetadataBackup_FullMethodName  = "/olap.v1.OlapService/TriggerMetadataBackup"
	OlapService_ListMetadataBackups_FullMethodName    = "/olap.v1.OlapService/ListMetadataBackups"
	OlapService_RecoverMetadata_FullMethodName        = "/olap.v1.OlapService/RecoverMetadata"
	OlapService_GetMetadataStatus_FullMethodName      = "/olap.v1.OlapService/GetMetadataStatus"
	OlapService_ValidateMetadataBackup_FullMethodName = "/olap.v1.OlapService/ValidateMetadataBackup"
)

// OlapServiceClient is the client API for OlapService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OlapServiceClient interface {
	// 写入数据
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	// 执行查询
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// 手动触发数据备份
	TriggerBackup(ctx context.Context, in *TriggerBackupRequest, opts ...grpc.CallOption) (*TriggerBackupResponse, error)
	// 从备份节点恢复数据
	RecoverData(ctx context.Context, in *RecoverDataRequest, opts ...grpc.CallOption) (*RecoverDataResponse, error)
	// 健康检查
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// 获取系统统计信息
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
	// 获取集群节点信息
	GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesResponse, error)
	// 表管理接口
	CreateTable(ctx context.Context, in *CreateTableRequest, opts ...grpc.CallOption) (*CreateTableResponse, error)
	DropTable(ctx context.Context, in *DropTableRequest, opts ...grpc.CallOption) (*DropTableResponse, error)
	ListTables(ctx context.Context, in *ListTablesRequest, opts ...grpc.CallOption) (*ListTablesResponse, error)
	DescribeTable(ctx context.Context, in *DescribeTableRequest, opts ...grpc.CallOption) (*DescribeTableResponse, error)
	// 元数据管理接口
	TriggerMetadataBackup(ctx context.Context, in *TriggerMetadataBackupRequest, opts ...grpc.CallOption) (*TriggerMetadataBackupResponse, error)
	ListMetadataBackups(ctx context.Context, in *ListMetadataBackupsRequest, opts ...grpc.CallOption) (*ListMetadataBackupsResponse, error)
	RecoverMetadata(ctx context.Context, in *RecoverMetadataRequest, opts ...grpc.CallOption) (*RecoverMetadataResponse, error)
	GetMetadataStatus(ctx context.Context, in *GetMetadataStatusRequest, opts ...grpc.CallOption) (*MetadataStatusResponse, error)
	ValidateMetadataBackup(ctx context.Context, in *ValidateMetadataBackupRequest, opts ...grpc.CallOption) (*ValidateMetadataBackupResponse, error)
}

type olapServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOlapServiceClient(cc grpc.ClientConnInterface) OlapServiceClient {
	return &olapServiceClient{cc}
}

func (c *olapServiceClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, OlapService_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *olapServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, OlapService_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *olapServiceClient) TriggerBackup(ctx context.Context, in *TriggerBackupRequest, opts ...grpc.CallOption) (*TriggerBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerBackupResponse)
	err := c.cc.Invoke(ctx, OlapService_TriggerBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *olapServiceClient) RecoverData(ctx context.Context, in *RecoverDataRequest, opts ...grpc.CallOption) (*RecoverDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecoverDataResponse)
	err := c.cc.Invoke(ctx, OlapService_RecoverData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *olapServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, OlapService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *olapServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, OlapService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *olapServiceClient) GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodesResponse)
	err := c.cc.Invoke(ctx, OlapService_GetNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *olapServiceClient) CreateTable(ctx context.Context, in *CreateTableRequest, opts ...grpc.CallOption) (*CreateTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTableResponse)
	err := c.cc.Invoke(ctx, OlapService_CreateTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *olapServiceClient) DropTable(ctx context.Context, in *DropTableRequest, opts ...grpc.CallOption) (*DropTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropTableResponse)
	err := c.cc.Invoke(ctx, OlapService_DropTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *olapServiceClient) ListTables(ctx context.Context, in *ListTablesRequest, opts ...grpc.CallOption) (*ListTablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTablesResponse)
	err := c.cc.Invoke(ctx, OlapService_ListTables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *olapServiceClient) DescribeTable(ctx context.Context, in *DescribeTableRequest, opts ...grpc.CallOption) (*DescribeTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeTableResponse)
	err := c.cc.Invoke(ctx, OlapService_DescribeTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *olapServiceClient) TriggerMetadataBackup(ctx context.Context, in *TriggerMetadataBackupRequest, opts ...grpc.CallOption) (*TriggerMetadataBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerMetadataBackupResponse)
	err := c.cc.Invoke(ctx, OlapService_TriggerMetadataBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *olapServiceClient) ListMetadataBackups(ctx context.Context, in *ListMetadataBackupsRequest, opts ...grpc.CallOption) (*ListMetadataBackupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMetadataBackupsResponse)
	err := c.cc.Invoke(ctx, OlapService_ListMetadataBackups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *olapServiceClient) RecoverMetadata(ctx context.Context, in *RecoverMetadataRequest, opts ...grpc.CallOption) (*RecoverMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecoverMetadataResponse)
	err := c.cc.Invoke(ctx, OlapService_RecoverMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *olapServiceClient) GetMetadataStatus(ctx context.Context, in *GetMetadataStatusRequest, opts ...grpc.CallOption) (*MetadataStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetadataStatusResponse)
	err := c.cc.Invoke(ctx, OlapService_GetMetadataStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *olapServiceClient) ValidateMetadataBackup(ctx context.Context, in *ValidateMetadataBackupRequest, opts ...grpc.CallOption) (*ValidateMetadataBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateMetadataBackupResponse)
	err := c.cc.Invoke(ctx, OlapService_ValidateMetadataBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OlapServiceServer is the server API for OlapService service.
// All implementations must embed UnimplementedOlapServiceServer
// for forward compatibility.
type OlapServiceServer interface {
	// 写入数据
	Write(context.Context, *WriteRequest) (*WriteResponse, error)
	// 执行查询
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	// 手动触发数据备份
	TriggerBackup(context.Context, *TriggerBackupRequest) (*TriggerBackupResponse, error)
	// 从备份节点恢复数据
	RecoverData(context.Context, *RecoverDataRequest) (*RecoverDataResponse, error)
	// 健康检查
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// 获取系统统计信息
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	// 获取集群节点信息
	GetNodes(context.Context, *GetNodesRequest) (*GetNodesResponse, error)
	// 表管理接口
	CreateTable(context.Context, *CreateTableRequest) (*CreateTableResponse, error)
	DropTable(context.Context, *DropTableRequest) (*DropTableResponse, error)
	ListTables(context.Context, *ListTablesRequest) (*ListTablesResponse, error)
	DescribeTable(context.Context, *DescribeTableRequest) (*DescribeTableResponse, error)
	// 元数据管理接口
	TriggerMetadataBackup(context.Context, *TriggerMetadataBackupRequest) (*TriggerMetadataBackupResponse, error)
	ListMetadataBackups(context.Context, *ListMetadataBackupsRequest) (*ListMetadataBackupsResponse, error)
	RecoverMetadata(context.Context, *RecoverMetadataRequest) (*RecoverMetadataResponse, error)
	GetMetadataStatus(context.Context, *GetMetadataStatusRequest) (*MetadataStatusResponse, error)
	ValidateMetadataBackup(context.Context, *ValidateMetadataBackupRequest) (*ValidateMetadataBackupResponse, error)
	mustEmbedUnimplementedOlapServiceServer()
}

// UnimplementedOlapServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOlapServiceServer struct{}

func (UnimplementedOlapServiceServer) Write(context.Context, *WriteRequest) (*WriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedOlapServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedOlapServiceServer) TriggerBackup(context.Context, *TriggerBackupRequest) (*TriggerBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerBackup not implemented")
}
func (UnimplementedOlapServiceServer) RecoverData(context.Context, *RecoverDataRequest) (*RecoverDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecoverData not implemented")
}
func (UnimplementedOlapServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedOlapServiceServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedOlapServiceServer) GetNodes(context.Context, *GetNodesRequest) (*GetNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodes not implemented")
}
func (UnimplementedOlapServiceServer) CreateTable(context.Context, *CreateTableRequest) (*CreateTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTable not implemented")
}
func (UnimplementedOlapServiceServer) DropTable(context.Context, *DropTableRequest) (*DropTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropTable not implemented")
}
func (UnimplementedOlapServiceServer) ListTables(context.Context, *ListTablesRequest) (*ListTablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTables not implemented")
}
func (UnimplementedOlapServiceServer) DescribeTable(context.Context, *DescribeTableRequest) (*DescribeTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeTable not implemented")
}
func (UnimplementedOlapServiceServer) TriggerMetadataBackup(context.Context, *TriggerMetadataBackupRequest) (*TriggerMetadataBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerMetadataBackup not implemented")
}
func (UnimplementedOlapServiceServer) ListMetadataBackups(context.Context, *ListMetadataBackupsRequest) (*ListMetadataBackupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMetadataBackups not implemented")
}
func (UnimplementedOlapServiceServer) RecoverMetadata(context.Context, *RecoverMetadataRequest) (*RecoverMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecoverMetadata not implemented")
}
func (UnimplementedOlapServiceServer) GetMetadataStatus(context.Context, *GetMetadataStatusRequest) (*MetadataStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetadataStatus not implemented")
}
func (UnimplementedOlapServiceServer) ValidateMetadataBackup(context.Context, *ValidateMetadataBackupRequest) (*ValidateMetadataBackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateMetadataBackup not implemented")
}
func (UnimplementedOlapServiceServer) mustEmbedUnimplementedOlapServiceServer() {}
func (UnimplementedOlapServiceServer) testEmbeddedByValue()                     {}

// UnsafeOlapServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OlapServiceServer will
// result in compilation errors.
type UnsafeOlapServiceServer interface {
	mustEmbedUnimplementedOlapServiceServer()
}

func RegisterOlapServiceServer(s grpc.ServiceRegistrar, srv OlapServiceServer) {
	// If the following call pancis, it indicates UnimplementedOlapServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OlapService_ServiceDesc, srv)
}

func _OlapService_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OlapServiceServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OlapService_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OlapServiceServer).Write(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OlapService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OlapServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OlapService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OlapServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OlapService_TriggerBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OlapServiceServer).TriggerBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OlapService_TriggerBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OlapServiceServer).TriggerBackup(ctx, req.(*TriggerBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OlapService_RecoverData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OlapServiceServer).RecoverData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OlapService_RecoverData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OlapServiceServer).RecoverData(ctx, req.(*RecoverDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OlapService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OlapServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OlapService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OlapServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OlapService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OlapServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OlapService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OlapServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OlapService_GetNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OlapServiceServer).GetNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OlapService_GetNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OlapServiceServer).GetNodes(ctx, req.(*GetNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OlapService_CreateTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OlapServiceServer).CreateTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OlapService_CreateTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OlapServiceServer).CreateTable(ctx, req.(*CreateTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OlapService_DropTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OlapServiceServer).DropTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OlapService_DropTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OlapServiceServer).DropTable(ctx, req.(*DropTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OlapService_ListTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OlapServiceServer).ListTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OlapService_ListTables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OlapServiceServer).ListTables(ctx, req.(*ListTablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OlapService_DescribeTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OlapServiceServer).DescribeTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OlapService_DescribeTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OlapServiceServer).DescribeTable(ctx, req.(*DescribeTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OlapService_TriggerMetadataBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerMetadataBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OlapServiceServer).TriggerMetadataBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OlapService_TriggerMetadataBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OlapServiceServer).TriggerMetadataBackup(ctx, req.(*TriggerMetadataBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OlapService_ListMetadataBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMetadataBackupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OlapServiceServer).ListMetadataBackups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OlapService_ListMetadataBackups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OlapServiceServer).ListMetadataBackups(ctx, req.(*ListMetadataBackupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OlapService_RecoverMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OlapServiceServer).RecoverMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OlapService_RecoverMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OlapServiceServer).RecoverMetadata(ctx, req.(*RecoverMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OlapService_GetMetadataStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetadataStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OlapServiceServer).GetMetadataStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OlapService_GetMetadataStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OlapServiceServer).GetMetadataStatus(ctx, req.(*GetMetadataStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OlapService_ValidateMetadataBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateMetadataBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OlapServiceServer).ValidateMetadataBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OlapService_ValidateMetadataBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OlapServiceServer).ValidateMetadataBackup(ctx, req.(*ValidateMetadataBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OlapService_ServiceDesc is the grpc.ServiceDesc for OlapService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OlapService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "olap.v1.OlapService",
	HandlerType: (*OlapServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Write",
			Handler:    _OlapService_Write_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _OlapService_Query_Handler,
		},
		{
			MethodName: "TriggerBackup",
			Handler:    _OlapService_TriggerBackup_Handler,
		},
		{
			MethodName: "RecoverData",
			Handler:    _OlapService_RecoverData_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _OlapService_HealthCheck_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _OlapService_GetStats_Handler,
		},
		{
			MethodName: "GetNodes",
			Handler:    _OlapService_GetNodes_Handler,
		},
		{
			MethodName: "CreateTable",
			Handler:    _OlapService_CreateTable_Handler,
		},
		{
			MethodName: "DropTable",
			Handler:    _OlapService_DropTable_Handler,
		},
		{
			MethodName: "ListTables",
			Handler:    _OlapService_ListTables_Handler,
		},
		{
			MethodName: "DescribeTable",
			Handler:    _OlapService_DescribeTable_Handler,
		},
		{
			MethodName: "TriggerMetadataBackup",
			Handler:    _OlapService_TriggerMetadataBackup_Handler,
		},
		{
			MethodName: "ListMetadataBackups",
			Handler:    _OlapService_ListMetadataBackups_Handler,
		},
		{
			MethodName: "RecoverMetadata",
			Handler:    _OlapService_RecoverMetadata_Handler,
		},
		{
			MethodName: "GetMetadataStatus",
			Handler:    _OlapService_GetMetadataStatus_Handler,
		},
		{
			MethodName: "ValidateMetadataBackup",
			Handler:    _OlapService_ValidateMetadataBackup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "olap.proto",
}
