// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: olap.proto

package olapv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_olap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_olap_proto_rawDescGZIP(), []int{0}
}

func (x *WriteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WriteRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *WriteRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_olap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_olap_proto_rawDescGZIP(), []int{1}
}

func (x *WriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WriteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_olap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_olap_proto_rawDescGZIP(), []int{2}
}

func (x *QueryRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

type QueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 结果可以用JSON字符串或者更复杂的结构表示
	ResultJson    string `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_olap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_olap_proto_rawDescGZIP(), []int{3}
}

func (x *QueryResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

type TriggerBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Day           string                 `protobuf:"bytes,2,opt,name=day,proto3" json:"day,omitempty"` // format: YYYY-MM-DD
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerBackupRequest) Reset() {
	*x = TriggerBackupRequest{}
	mi := &file_olap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerBackupRequest) ProtoMessage() {}

func (x *TriggerBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerBackupRequest.ProtoReflect.Descriptor instead.
func (*TriggerBackupRequest) Descriptor() ([]byte, []int) {
	return file_olap_proto_rawDescGZIP(), []int{4}
}

func (x *TriggerBackupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TriggerBackupRequest) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

type TriggerBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FilesBackedUp int32                  `protobuf:"varint,3,opt,name=files_backed_up,json=filesBackedUp,proto3" json:"files_backed_up,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerBackupResponse) Reset() {
	*x = TriggerBackupResponse{}
	mi := &file_olap_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerBackupResponse) ProtoMessage() {}

func (x *TriggerBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olap_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerBackupResponse.ProtoReflect.Descriptor instead.
func (*TriggerBackupResponse) Descriptor() ([]byte, []int) {
	return file_olap_proto_rawDescGZIP(), []int{5}
}

func (x *TriggerBackupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TriggerBackupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TriggerBackupResponse) GetFilesBackedUp() int32 {
	if x != nil {
		return x.FilesBackedUp
	}
	return 0
}

type RecoverDataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 恢复模式：可以按ID范围、时间范围或节点ID恢复
	//
	// Types that are valid to be assigned to RecoveryMode:
	//
	//	*RecoverDataRequest_NodeId
	//	*RecoverDataRequest_IdRange
	//	*RecoverDataRequest_TimeRange
	RecoveryMode   isRecoverDataRequest_RecoveryMode `protobuf_oneof:"recovery_mode"`
	ForceOverwrite bool                              `protobuf:"varint,4,opt,name=force_overwrite,json=forceOverwrite,proto3" json:"force_overwrite,omitempty"` // 是否强制覆盖已存在的数据
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecoverDataRequest) Reset() {
	*x = RecoverDataRequest{}
	mi := &file_olap_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoverDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverDataRequest) ProtoMessage() {}

func (x *RecoverDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olap_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverDataRequest.ProtoReflect.Descriptor instead.
func (*RecoverDataRequest) Descriptor() ([]byte, []int) {
	return file_olap_proto_rawDescGZIP(), []int{6}
}

func (x *RecoverDataRequest) GetRecoveryMode() isRecoverDataRequest_RecoveryMode {
	if x != nil {
		return x.RecoveryMode
	}
	return nil
}

func (x *RecoverDataRequest) GetNodeId() string {
	if x != nil {
		if x, ok := x.RecoveryMode.(*RecoverDataRequest_NodeId); ok {
			return x.NodeId
		}
	}
	return ""
}

func (x *RecoverDataRequest) GetIdRange() *IdRangeFilter {
	if x != nil {
		if x, ok := x.RecoveryMode.(*RecoverDataRequest_IdRange); ok {
			return x.IdRange
		}
	}
	return nil
}

func (x *RecoverDataRequest) GetTimeRange() *TimeRangeFilter {
	if x != nil {
		if x, ok := x.RecoveryMode.(*RecoverDataRequest_TimeRange); ok {
			return x.TimeRange
		}
	}
	return nil
}

func (x *RecoverDataRequest) GetForceOverwrite() bool {
	if x != nil {
		return x.ForceOverwrite
	}
	return false
}

type isRecoverDataRequest_RecoveryMode interface {
	isRecoverDataRequest_RecoveryMode()
}

type RecoverDataRequest_NodeId struct {
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3,oneof"` // 恢复特定节点的所有数据
}

type RecoverDataRequest_IdRange struct {
	IdRange *IdRangeFilter `protobuf:"bytes,2,opt,name=id_range,json=idRange,proto3,oneof"` // 恢复特定ID范围的数据
}

type RecoverDataRequest_TimeRange struct {
	TimeRange *TimeRangeFilter `protobuf:"bytes,3,opt,name=time_range,json=timeRange,proto3,oneof"` // 恢复特定时间范围的数据
}

func (*RecoverDataRequest_NodeId) isRecoverDataRequest_RecoveryMode() {}

func (*RecoverDataRequest_IdRange) isRecoverDataRequest_RecoveryMode() {}

func (*RecoverDataRequest_TimeRange) isRecoverDataRequest_RecoveryMode() {}

type IdRangeFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`                              // 具体的ID列表
	IdPattern     string                 `protobuf:"bytes,2,opt,name=id_pattern,json=idPattern,proto3" json:"id_pattern,omitempty"` // ID模式匹配，如 "user-*"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdRangeFilter) Reset() {
	*x = IdRangeFilter{}
	mi := &file_olap_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdRangeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdRangeFilter) ProtoMessage() {}

func (x *IdRangeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_olap_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdRangeFilter.ProtoReflect.Descriptor instead.
func (*IdRangeFilter) Descriptor() ([]byte, []int) {
	return file_olap_proto_rawDescGZIP(), []int{7}
}

func (x *IdRangeFilter) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *IdRangeFilter) GetIdPattern() string {
	if x != nil {
		return x.IdPattern
	}
	return ""
}

type TimeRangeFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // 开始日期 YYYY-MM-DD
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // 结束日期 YYYY-MM-DD
	Ids           []string               `protobuf:"bytes,3,rep,name=ids,proto3" json:"ids,omitempty"`                              // 可选：限制特定ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRangeFilter) Reset() {
	*x = TimeRangeFilter{}
	mi := &file_olap_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRangeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRangeFilter) ProtoMessage() {}

func (x *TimeRangeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_olap_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRangeFilter.ProtoReflect.Descriptor instead.
func (*TimeRangeFilter) Descriptor() ([]byte, []int) {
	return file_olap_proto_rawDescGZIP(), []int{8}
}

func (x *TimeRangeFilter) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *TimeRangeFilter) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *TimeRangeFilter) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type RecoverDataResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FilesRecovered int32                  `protobuf:"varint,3,opt,name=files_recovered,json=filesRecovered,proto3" json:"files_recovered,omitempty"`
	RecoveredKeys  []string               `protobuf:"bytes,4,rep,name=recovered_keys,json=recoveredKeys,proto3" json:"recovered_keys,omitempty"` // 恢复的数据键列表
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecoverDataResponse) Reset() {
	*x = RecoverDataResponse{}
	mi := &file_olap_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoverDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverDataResponse) ProtoMessage() {}

func (x *RecoverDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olap_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverDataResponse.ProtoReflect.Descriptor instead.
func (*RecoverDataResponse) Descriptor() ([]byte, []int) {
	return file_olap_proto_rawDescGZIP(), []int{9}
}

func (x *RecoverDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RecoverDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RecoverDataResponse) GetFilesRecovered() int32 {
	if x != nil {
		return x.FilesRecovered
	}
	return 0
}

func (x *RecoverDataResponse) GetRecoveredKeys() []string {
	if x != nil {
		return x.RecoveredKeys
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_olap_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olap_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_olap_proto_rawDescGZIP(), []int{10}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                                                             // 健康状态：healthy, unhealthy
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                       // 检查时间戳
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                                                                           // 服务版本
	Details       map[string]string      `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 详细信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_olap_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olap_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_olap_proto_rawDescGZIP(), []int{11}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_olap_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olap_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_olap_proto_rawDescGZIP(), []int{12}
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                                                   // 统计时间戳
	BufferStats   map[string]int64       `protobuf:"bytes,2,rep,name=buffer_stats,json=bufferStats,proto3" json:"buffer_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 缓冲区统计
	RedisStats    map[string]int64       `protobuf:"bytes,3,rep,name=redis_stats,json=redisStats,proto3" json:"redis_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`    // Redis统计
	MinioStats    map[string]int64       `protobuf:"bytes,4,rep,name=minio_stats,json=minioStats,proto3" json:"minio_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`    // MinIO统计
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_olap_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olap_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_olap_proto_rawDescGZIP(), []int{13}
}

func (x *GetStatsResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *GetStatsResponse) GetBufferStats() map[string]int64 {
	if x != nil {
		return x.BufferStats
	}
	return nil
}

func (x *GetStatsResponse) GetRedisStats() map[string]int64 {
	if x != nil {
		return x.RedisStats
	}
	return nil
}

func (x *GetStatsResponse) GetMinioStats() map[string]int64 {
	if x != nil {
		return x.MinioStats
	}
	return nil
}

type GetNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodesRequest) Reset() {
	*x = GetNodesRequest{}
	mi := &file_olap_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesRequest) ProtoMessage() {}

func (x *GetNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olap_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesRequest.ProtoReflect.Descriptor instead.
func (*GetNodesRequest) Descriptor() ([]byte, []int) {
	return file_olap_proto_rawDescGZIP(), []int{14}
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                              // 节点ID
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                      // 节点状态
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                          // 节点类型
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`                    // 节点地址
	LastSeen      int64                  `protobuf:"varint,5,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"` // 最后活跃时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_olap_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_olap_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_olap_proto_rawDescGZIP(), []int{15}
}

func (x *NodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NodeInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeInfo) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

type GetNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`  // 节点列表
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 节点总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodesResponse) Reset() {
	*x = GetNodesResponse{}
	mi := &file_olap_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesResponse) ProtoMessage() {}

func (x *GetNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olap_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesResponse.ProtoReflect.Descriptor instead.
func (*GetNodesResponse) Descriptor() ([]byte, []int) {
	return file_olap_proto_rawDescGZIP(), []int{16}
}

func (x *GetNodesResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GetNodesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_olap_proto protoreflect.FileDescriptor

const file_olap_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"olap.proto\x12\aolap.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8b\x01\n" +
	"\fWriteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x121\n" +
	"\apayload\x18\x03 \x01(\v2\x17.google.protobuf.StructR\apayload\"C\n" +
	"\rWriteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\" \n" +
	"\fQueryRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\"0\n" +
	"\rQueryResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\tR\n" +
	"resultJson\"8\n" +
	"\x14TriggerBackupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03day\x18\x02 \x01(\tR\x03day\"s\n" +
	"\x15TriggerBackupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x0ffiles_backed_up\x18\x03 \x01(\x05R\rfilesBackedUp\"\xd9\x01\n" +
	"\x12RecoverDataRequest\x12\x19\n" +
	"\anode_id\x18\x01 \x01(\tH\x00R\x06nodeId\x123\n" +
	"\bid_range\x18\x02 \x01(\v2\x16.olap.v1.IdRangeFilterH\x00R\aidRange\x129\n" +
	"\n" +
	"time_range\x18\x03 \x01(\v2\x18.olap.v1.TimeRangeFilterH\x00R\ttimeRange\x12'\n" +
	"\x0fforce_overwrite\x18\x04 \x01(\bR\x0eforceOverwriteB\x0f\n" +
	"\rrecovery_mode\"@\n" +
	"\rIdRangeFilter\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x1d\n" +
	"\n" +
	"id_pattern\x18\x02 \x01(\tR\tidPattern\"]\n" +
	"\x0fTimeRangeFilter\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\x12\x10\n" +
	"\x03ids\x18\x03 \x03(\tR\x03ids\"\x99\x01\n" +
	"\x13RecoverDataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0ffiles_recovered\x18\x03 \x01(\x05R\x0efilesRecovered\x12%\n" +
	"\x0erecovered_keys\x18\x04 \x03(\tR\rrecoveredKeys\"\x14\n" +
	"\x12HealthCheckRequest\"\xe6\x01\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12C\n" +
	"\adetails\x18\x04 \x03(\v2).olap.v1.HealthCheckResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x11\n" +
	"\x0fGetStatsRequest\"\xd5\x03\n" +
	"\x10GetStatsResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12M\n" +
	"\fbuffer_stats\x18\x02 \x03(\v2*.olap.v1.GetStatsResponse.BufferStatsEntryR\vbufferStats\x12J\n" +
	"\vredis_stats\x18\x03 \x03(\v2).olap.v1.GetStatsResponse.RedisStatsEntryR\n" +
	"redisStats\x12J\n" +
	"\vminio_stats\x18\x04 \x03(\v2).olap.v1.GetStatsResponse.MinioStatsEntryR\n" +
	"minioStats\x1a>\n" +
	"\x10BufferStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a=\n" +
	"\x0fRedisStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a=\n" +
	"\x0fMinioStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x11\n" +
	"\x0fGetNodesRequest\"}\n" +
	"\bNodeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x1b\n" +
	"\tlast_seen\x18\x05 \x01(\x03R\blastSeen\"Q\n" +
	"\x10GetNodesResponse\x12'\n" +
	"\x05nodes\x18\x01 \x03(\v2\x11.olap.v1.NodeInfoR\x05nodes\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\xe3\x03\n" +
	"\vOlapService\x126\n" +
	"\x05Write\x12\x15.olap.v1.WriteRequest\x1a\x16.olap.v1.WriteResponse\x126\n" +
	"\x05Query\x12\x15.olap.v1.QueryRequest\x1a\x16.olap.v1.QueryResponse\x12N\n" +
	"\rTriggerBackup\x12\x1d.olap.v1.TriggerBackupRequest\x1a\x1e.olap.v1.TriggerBackupResponse\x12H\n" +
	"\vRecoverData\x12\x1b.olap.v1.RecoverDataRequest\x1a\x1c.olap.v1.RecoverDataResponse\x12H\n" +
	"\vHealthCheck\x12\x1b.olap.v1.HealthCheckRequest\x1a\x1c.olap.v1.HealthCheckResponse\x12?\n" +
	"\bGetStats\x12\x18.olap.v1.GetStatsRequest\x1a\x19.olap.v1.GetStatsResponse\x12?\n" +
	"\bGetNodes\x12\x18.olap.v1.GetNodesRequest\x1a\x19.olap.v1.GetNodesResponseB\vZ\t./;olapv1b\x06proto3"

var (
	file_olap_proto_rawDescOnce sync.Once
	file_olap_proto_rawDescData []byte
)

func file_olap_proto_rawDescGZIP() []byte {
	file_olap_proto_rawDescOnce.Do(func() {
		file_olap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_olap_proto_rawDesc), len(file_olap_proto_rawDesc)))
	})
	return file_olap_proto_rawDescData
}

var file_olap_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_olap_proto_goTypes = []any{
	(*WriteRequest)(nil),          // 0: olap.v1.WriteRequest
	(*WriteResponse)(nil),         // 1: olap.v1.WriteResponse
	(*QueryRequest)(nil),          // 2: olap.v1.QueryRequest
	(*QueryResponse)(nil),         // 3: olap.v1.QueryResponse
	(*TriggerBackupRequest)(nil),  // 4: olap.v1.TriggerBackupRequest
	(*TriggerBackupResponse)(nil), // 5: olap.v1.TriggerBackupResponse
	(*RecoverDataRequest)(nil),    // 6: olap.v1.RecoverDataRequest
	(*IdRangeFilter)(nil),         // 7: olap.v1.IdRangeFilter
	(*TimeRangeFilter)(nil),       // 8: olap.v1.TimeRangeFilter
	(*RecoverDataResponse)(nil),   // 9: olap.v1.RecoverDataResponse
	(*HealthCheckRequest)(nil),    // 10: olap.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 11: olap.v1.HealthCheckResponse
	(*GetStatsRequest)(nil),       // 12: olap.v1.GetStatsRequest
	(*GetStatsResponse)(nil),      // 13: olap.v1.GetStatsResponse
	(*GetNodesRequest)(nil),       // 14: olap.v1.GetNodesRequest
	(*NodeInfo)(nil),              // 15: olap.v1.NodeInfo
	(*GetNodesResponse)(nil),      // 16: olap.v1.GetNodesResponse
	nil,                           // 17: olap.v1.HealthCheckResponse.DetailsEntry
	nil,                           // 18: olap.v1.GetStatsResponse.BufferStatsEntry
	nil,                           // 19: olap.v1.GetStatsResponse.RedisStatsEntry
	nil,                           // 20: olap.v1.GetStatsResponse.MinioStatsEntry
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 22: google.protobuf.Struct
}
var file_olap_proto_depIdxs = []int32{
	21, // 0: olap.v1.WriteRequest.timestamp:type_name -> google.protobuf.Timestamp
	22, // 1: olap.v1.WriteRequest.payload:type_name -> google.protobuf.Struct
	7,  // 2: olap.v1.RecoverDataRequest.id_range:type_name -> olap.v1.IdRangeFilter
	8,  // 3: olap.v1.RecoverDataRequest.time_range:type_name -> olap.v1.TimeRangeFilter
	17, // 4: olap.v1.HealthCheckResponse.details:type_name -> olap.v1.HealthCheckResponse.DetailsEntry
	18, // 5: olap.v1.GetStatsResponse.buffer_stats:type_name -> olap.v1.GetStatsResponse.BufferStatsEntry
	19, // 6: olap.v1.GetStatsResponse.redis_stats:type_name -> olap.v1.GetStatsResponse.RedisStatsEntry
	20, // 7: olap.v1.GetStatsResponse.minio_stats:type_name -> olap.v1.GetStatsResponse.MinioStatsEntry
	15, // 8: olap.v1.GetNodesResponse.nodes:type_name -> olap.v1.NodeInfo
	0,  // 9: olap.v1.OlapService.Write:input_type -> olap.v1.WriteRequest
	2,  // 10: olap.v1.OlapService.Query:input_type -> olap.v1.QueryRequest
	4,  // 11: olap.v1.OlapService.TriggerBackup:input_type -> olap.v1.TriggerBackupRequest
	6,  // 12: olap.v1.OlapService.RecoverData:input_type -> olap.v1.RecoverDataRequest
	10, // 13: olap.v1.OlapService.HealthCheck:input_type -> olap.v1.HealthCheckRequest
	12, // 14: olap.v1.OlapService.GetStats:input_type -> olap.v1.GetStatsRequest
	14, // 15: olap.v1.OlapService.GetNodes:input_type -> olap.v1.GetNodesRequest
	1,  // 16: olap.v1.OlapService.Write:output_type -> olap.v1.WriteResponse
	3,  // 17: olap.v1.OlapService.Query:output_type -> olap.v1.QueryResponse
	5,  // 18: olap.v1.OlapService.TriggerBackup:output_type -> olap.v1.TriggerBackupResponse
	9,  // 19: olap.v1.OlapService.RecoverData:output_type -> olap.v1.RecoverDataResponse
	11, // 20: olap.v1.OlapService.HealthCheck:output_type -> olap.v1.HealthCheckResponse
	13, // 21: olap.v1.OlapService.GetStats:output_type -> olap.v1.GetStatsResponse
	16, // 22: olap.v1.OlapService.GetNodes:output_type -> olap.v1.GetNodesResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_olap_proto_init() }
func file_olap_proto_init() {
	if File_olap_proto != nil {
		return
	}
	file_olap_proto_msgTypes[6].OneofWrappers = []any{
		(*RecoverDataRequest_NodeId)(nil),
		(*RecoverDataRequest_IdRange)(nil),
		(*RecoverDataRequest_TimeRange)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_olap_proto_rawDesc), len(file_olap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_olap_proto_goTypes,
		DependencyIndexes: file_olap_proto_depIdxs,
		MessageInfos:      file_olap_proto_msgTypes,
	}.Build()
	File_olap_proto = out.File
	file_olap_proto_goTypes = nil
	file_olap_proto_depIdxs = nil
}
