// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.28.3
// source: api/proto/olap/v1/olap.proto

package olapv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload   *structpb.Struct       `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_olap_v1_olap_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_olap_v1_olap_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_olap_v1_olap_proto_rawDescGZIP(), []int{0}
}

func (x *WriteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WriteRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *WriteRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WriteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_olap_v1_olap_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_olap_v1_olap_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_olap_v1_olap_proto_rawDescGZIP(), []int{1}
}

func (x *WriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WriteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type QueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sql string `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_olap_v1_olap_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_olap_v1_olap_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_olap_v1_olap_proto_rawDescGZIP(), []int{2}
}

func (x *QueryRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 结果可以用JSON字符串或者更复杂的结构表示
	ResultJson string `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_olap_v1_olap_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_olap_v1_olap_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_olap_v1_olap_proto_rawDescGZIP(), []int{3}
}

func (x *QueryResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

type TriggerBackupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Day string `protobuf:"bytes,2,opt,name=day,proto3" json:"day,omitempty"` // format: YYYY-MM-DD
}

func (x *TriggerBackupRequest) Reset() {
	*x = TriggerBackupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_olap_v1_olap_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TriggerBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerBackupRequest) ProtoMessage() {}

func (x *TriggerBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_olap_v1_olap_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerBackupRequest.ProtoReflect.Descriptor instead.
func (*TriggerBackupRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_olap_v1_olap_proto_rawDescGZIP(), []int{4}
}

func (x *TriggerBackupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TriggerBackupRequest) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

type TriggerBackupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success       bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FilesBackedUp int32  `protobuf:"varint,3,opt,name=files_backed_up,json=filesBackedUp,proto3" json:"files_backed_up,omitempty"`
}

func (x *TriggerBackupResponse) Reset() {
	*x = TriggerBackupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_olap_v1_olap_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TriggerBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerBackupResponse) ProtoMessage() {}

func (x *TriggerBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_olap_v1_olap_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerBackupResponse.ProtoReflect.Descriptor instead.
func (*TriggerBackupResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_olap_v1_olap_proto_rawDescGZIP(), []int{5}
}

func (x *TriggerBackupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TriggerBackupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TriggerBackupResponse) GetFilesBackedUp() int32 {
	if x != nil {
		return x.FilesBackedUp
	}
	return 0
}

type RecoverDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 恢复模式：可以按ID范围、时间范围或节点ID恢复
	//
	// Types that are assignable to RecoveryMode:
	//
	//	*RecoverDataRequest_NodeId
	//	*RecoverDataRequest_IdRange
	//	*RecoverDataRequest_TimeRange
	RecoveryMode   isRecoverDataRequest_RecoveryMode `protobuf_oneof:"recovery_mode"`
	ForceOverwrite bool                              `protobuf:"varint,4,opt,name=force_overwrite,json=forceOverwrite,proto3" json:"force_overwrite,omitempty"` // 是否强制覆盖已存在的数据
}

func (x *RecoverDataRequest) Reset() {
	*x = RecoverDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_olap_v1_olap_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecoverDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverDataRequest) ProtoMessage() {}

func (x *RecoverDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_olap_v1_olap_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverDataRequest.ProtoReflect.Descriptor instead.
func (*RecoverDataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_olap_v1_olap_proto_rawDescGZIP(), []int{6}
}

func (m *RecoverDataRequest) GetRecoveryMode() isRecoverDataRequest_RecoveryMode {
	if m != nil {
		return m.RecoveryMode
	}
	return nil
}

func (x *RecoverDataRequest) GetNodeId() string {
	if x, ok := x.GetRecoveryMode().(*RecoverDataRequest_NodeId); ok {
		return x.NodeId
	}
	return ""
}

func (x *RecoverDataRequest) GetIdRange() *IdRangeFilter {
	if x, ok := x.GetRecoveryMode().(*RecoverDataRequest_IdRange); ok {
		return x.IdRange
	}
	return nil
}

func (x *RecoverDataRequest) GetTimeRange() *TimeRangeFilter {
	if x, ok := x.GetRecoveryMode().(*RecoverDataRequest_TimeRange); ok {
		return x.TimeRange
	}
	return nil
}

func (x *RecoverDataRequest) GetForceOverwrite() bool {
	if x != nil {
		return x.ForceOverwrite
	}
	return false
}

type isRecoverDataRequest_RecoveryMode interface {
	isRecoverDataRequest_RecoveryMode()
}

type RecoverDataRequest_NodeId struct {
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3,oneof"` // 恢复特定节点的所有数据
}

type RecoverDataRequest_IdRange struct {
	IdRange *IdRangeFilter `protobuf:"bytes,2,opt,name=id_range,json=idRange,proto3,oneof"` // 恢复特定ID范围的数据
}

type RecoverDataRequest_TimeRange struct {
	TimeRange *TimeRangeFilter `protobuf:"bytes,3,opt,name=time_range,json=timeRange,proto3,oneof"` // 恢复特定时间范围的数据
}

func (*RecoverDataRequest_NodeId) isRecoverDataRequest_RecoveryMode() {}

func (*RecoverDataRequest_IdRange) isRecoverDataRequest_RecoveryMode() {}

func (*RecoverDataRequest_TimeRange) isRecoverDataRequest_RecoveryMode() {}

type IdRangeFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids       []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`                              // 具体的ID列表
	IdPattern string   `protobuf:"bytes,2,opt,name=id_pattern,json=idPattern,proto3" json:"id_pattern,omitempty"` // ID模式匹配，如 "user-*"
}

func (x *IdRangeFilter) Reset() {
	*x = IdRangeFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_olap_v1_olap_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdRangeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdRangeFilter) ProtoMessage() {}

func (x *IdRangeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_olap_v1_olap_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdRangeFilter.ProtoReflect.Descriptor instead.
func (*IdRangeFilter) Descriptor() ([]byte, []int) {
	return file_api_proto_olap_v1_olap_proto_rawDescGZIP(), []int{7}
}

func (x *IdRangeFilter) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *IdRangeFilter) GetIdPattern() string {
	if x != nil {
		return x.IdPattern
	}
	return ""
}

type TimeRangeFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartDate string   `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // 开始日期 YYYY-MM-DD
	EndDate   string   `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // 结束日期 YYYY-MM-DD
	Ids       []string `protobuf:"bytes,3,rep,name=ids,proto3" json:"ids,omitempty"`                              // 可选：限制特定ID
}

func (x *TimeRangeFilter) Reset() {
	*x = TimeRangeFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_olap_v1_olap_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeRangeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRangeFilter) ProtoMessage() {}

func (x *TimeRangeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_olap_v1_olap_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRangeFilter.ProtoReflect.Descriptor instead.
func (*TimeRangeFilter) Descriptor() ([]byte, []int) {
	return file_api_proto_olap_v1_olap_proto_rawDescGZIP(), []int{8}
}

func (x *TimeRangeFilter) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *TimeRangeFilter) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *TimeRangeFilter) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type RecoverDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success        bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FilesRecovered int32    `protobuf:"varint,3,opt,name=files_recovered,json=filesRecovered,proto3" json:"files_recovered,omitempty"`
	RecoveredKeys  []string `protobuf:"bytes,4,rep,name=recovered_keys,json=recoveredKeys,proto3" json:"recovered_keys,omitempty"` // 恢复的数据键列表
}

func (x *RecoverDataResponse) Reset() {
	*x = RecoverDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_olap_v1_olap_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecoverDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverDataResponse) ProtoMessage() {}

func (x *RecoverDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_olap_v1_olap_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverDataResponse.ProtoReflect.Descriptor instead.
func (*RecoverDataResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_olap_v1_olap_proto_rawDescGZIP(), []int{9}
}

func (x *RecoverDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RecoverDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RecoverDataResponse) GetFilesRecovered() int32 {
	if x != nil {
		return x.FilesRecovered
	}
	return 0
}

func (x *RecoverDataResponse) GetRecoveredKeys() []string {
	if x != nil {
		return x.RecoveredKeys
	}
	return nil
}

var File_api_proto_olap_v1_olap_proto protoreflect.FileDescriptor

var file_api_proto_olap_v1_olap_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x6c, 0x61, 0x70,
	0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x6c, 0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x6f, 0x6c, 0x61, 0x70, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8b, 0x01, 0x0a, 0x0c, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x12, 0x31, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x22, 0x43, 0x0a, 0x0d, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x20, 0x0a, 0x0c, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x71, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x71, 0x6c, 0x22, 0x30, 0x0a, 0x0d, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4a, 0x73, 0x6f, 0x6e, 0x22, 0x38, 0x0a,
	0x14, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x64, 0x61, 0x79, 0x22, 0x73, 0x0a, 0x15, 0x54, 0x72, 0x69, 0x67, 0x67,
	0x65, 0x72, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x5f, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x64, 0x5f, 0x75, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x55, 0x70, 0x22, 0xd9, 0x01, 0x0a,
	0x12, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x33,
	0x0a, 0x08, 0x69, 0x64, 0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x6f, 0x6c, 0x61, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x07, 0x69, 0x64, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x72, 0x61, 0x6e, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x6c, 0x61, 0x70, 0x2e, 0x76,
	0x31, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x48, 0x00, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x27,
	0x0a, 0x0f, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x77, 0x72, 0x69, 0x74,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x4f, 0x76,
	0x65, 0x72, 0x77, 0x72, 0x69, 0x74, 0x65, 0x42, 0x0f, 0x0a, 0x0d, 0x72, 0x65, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x79, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x40, 0x0a, 0x0d, 0x49, 0x64, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x69,
	0x64, 0x5f, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x69, 0x64, 0x50, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x22, 0x5d, 0x0a, 0x0f, 0x54, 0x69,
	0x6d, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x65, 0x6e, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x99, 0x01, 0x0a, 0x13, 0x52, 0x65,
	0x63, 0x6f, 0x76, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x5f, 0x72,
	0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e,
	0x66, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x65, 0x64, 0x12, 0x25,
	0x0a, 0x0e, 0x72, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x65, 0x64, 0x5f, 0x6b, 0x65, 0x79, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x65,
	0x64, 0x4b, 0x65, 0x79, 0x73, 0x32, 0x97, 0x02, 0x0a, 0x0b, 0x4f, 0x6c, 0x61, 0x70, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x05, 0x57, 0x72, 0x69, 0x74, 0x65, 0x12, 0x15,
	0x2e, 0x6f, 0x6c, 0x61, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6f, 0x6c, 0x61, 0x70, 0x2e, 0x76, 0x31, 0x2e,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a,
	0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x15, 0x2e, 0x6f, 0x6c, 0x61, 0x70, 0x2e, 0x76, 0x31,
	0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x6f, 0x6c, 0x61, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0d, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72,
	0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x12, 0x1d, 0x2e, 0x6f, 0x6c, 0x61, 0x70, 0x2e, 0x76, 0x31,
	0x2e, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6f, 0x6c, 0x61, 0x70, 0x2e, 0x76, 0x31, 0x2e,
	0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0b, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x2e, 0x6f, 0x6c, 0x61, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x6f, 0x6c, 0x61, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x63, 0x6f,
	0x76, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x22, 0x5a, 0x20, 0x6d, 0x69, 0x6e, 0x49, 0x4f, 0x44, 0x42, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x6c, 0x61, 0x70, 0x2f, 0x76, 0x31, 0x3b, 0x6f, 0x6c, 0x61,
	0x70, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_olap_v1_olap_proto_rawDescOnce sync.Once
	file_api_proto_olap_v1_olap_proto_rawDescData = file_api_proto_olap_v1_olap_proto_rawDesc
)

func file_api_proto_olap_v1_olap_proto_rawDescGZIP() []byte {
	file_api_proto_olap_v1_olap_proto_rawDescOnce.Do(func() {
		file_api_proto_olap_v1_olap_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_olap_v1_olap_proto_rawDescData)
	})
	return file_api_proto_olap_v1_olap_proto_rawDescData
}

var file_api_proto_olap_v1_olap_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_olap_v1_olap_proto_goTypes = []interface{}{
	(*WriteRequest)(nil),          // 0: olap.v1.WriteRequest
	(*WriteResponse)(nil),         // 1: olap.v1.WriteResponse
	(*QueryRequest)(nil),          // 2: olap.v1.QueryRequest
	(*QueryResponse)(nil),         // 3: olap.v1.QueryResponse
	(*TriggerBackupRequest)(nil),  // 4: olap.v1.TriggerBackupRequest
	(*TriggerBackupResponse)(nil), // 5: olap.v1.TriggerBackupResponse
	(*RecoverDataRequest)(nil),    // 6: olap.v1.RecoverDataRequest
	(*IdRangeFilter)(nil),         // 7: olap.v1.IdRangeFilter
	(*TimeRangeFilter)(nil),       // 8: olap.v1.TimeRangeFilter
	(*RecoverDataResponse)(nil),   // 9: olap.v1.RecoverDataResponse
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 11: google.protobuf.Struct
}
var file_api_proto_olap_v1_olap_proto_depIdxs = []int32{
	10, // 0: olap.v1.WriteRequest.timestamp:type_name -> google.protobuf.Timestamp
	11, // 1: olap.v1.WriteRequest.payload:type_name -> google.protobuf.Struct
	7,  // 2: olap.v1.RecoverDataRequest.id_range:type_name -> olap.v1.IdRangeFilter
	8,  // 3: olap.v1.RecoverDataRequest.time_range:type_name -> olap.v1.TimeRangeFilter
	0,  // 4: olap.v1.OlapService.Write:input_type -> olap.v1.WriteRequest
	2,  // 5: olap.v1.OlapService.Query:input_type -> olap.v1.QueryRequest
	4,  // 6: olap.v1.OlapService.TriggerBackup:input_type -> olap.v1.TriggerBackupRequest
	6,  // 7: olap.v1.OlapService.RecoverData:input_type -> olap.v1.RecoverDataRequest
	1,  // 8: olap.v1.OlapService.Write:output_type -> olap.v1.WriteResponse
	3,  // 9: olap.v1.OlapService.Query:output_type -> olap.v1.QueryResponse
	5,  // 10: olap.v1.OlapService.TriggerBackup:output_type -> olap.v1.TriggerBackupResponse
	9,  // 11: olap.v1.OlapService.RecoverData:output_type -> olap.v1.RecoverDataResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_olap_v1_olap_proto_init() }
func file_api_proto_olap_v1_olap_proto_init() {
	if File_api_proto_olap_v1_olap_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_olap_v1_olap_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_olap_v1_olap_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_olap_v1_olap_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_olap_v1_olap_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_olap_v1_olap_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TriggerBackupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_olap_v1_olap_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TriggerBackupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_olap_v1_olap_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecoverDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_olap_v1_olap_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdRangeFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_olap_v1_olap_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeRangeFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_olap_v1_olap_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecoverDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_proto_olap_v1_olap_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*RecoverDataRequest_NodeId)(nil),
		(*RecoverDataRequest_IdRange)(nil),
		(*RecoverDataRequest_TimeRange)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_olap_v1_olap_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_olap_v1_olap_proto_goTypes,
		DependencyIndexes: file_api_proto_olap_v1_olap_proto_depIdxs,
		MessageInfos:      file_api_proto_olap_v1_olap_proto_msgTypes,
	}.Build()
	File_api_proto_olap_v1_olap_proto = out.File
	file_api_proto_olap_v1_olap_proto_rawDesc = nil
	file_api_proto_olap_v1_olap_proto_goTypes = nil
	file_api_proto_olap_v1_olap_proto_depIdxs = nil
}
