apiVersion: v1
kind: ConfigMap
metadata:
  name: miniodb-config
  namespace: miniodb-system
  labels:
    app.kubernetes.io/name: miniodb
    app.kubernetes.io/component: config
data:
  # MinIODB 应用配置
  config.yaml: |
    # MinIODB 配置文件
    app:
      name: "MinIODB"
      version: "1.0.0"
      environment: "production"
      log_level: "info"
    
    # 服务器配置
    server:
      grpc:
        port: 8080
        timeout: "30s"
      rest:
        port: 8081
        timeout: "30s"
        cors_enabled: true
      metrics:
        port: 9090
        path: "/metrics"
        enabled: true
    
    # Redis 配置
    redis:
      host: "redis-service"
      port: 6379
      db: 0
      pool_size: 10
      timeout: "5s"
      retry_attempts: 3
    
    # MinIO 主存储配置
    storage:
      primary:
        endpoint: "minio-service:9000"
        bucket: "miniodb-data"
        use_ssl: false
        timeout: "30s"
      backup:
        endpoint: "minio-backup-service:9000"
        bucket: "miniodb-backup"
        use_ssl: false
        timeout: "30s"
    
    # 缓冲区配置
    buffer:
      size: 1000
      timeout: "30s"
      batch_size: 100
      workers: 4
    
    # DuckDB 配置
    duckdb:
      memory_limit: "4GB"
      threads: 4
      temp_directory: "/tmp/duckdb"
    
    # 认证配置
    auth:
      mode: "jwt"
      jwt:
        expiration: "24h"
    
    # 监控配置
    monitoring:
      health_check_interval: "30s"
      metrics_collection_interval: "15s"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: miniodb-system
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: config
data:
  redis.conf: |
    # Redis 配置文件
    # 网络配置
    bind 0.0.0.0
    port 6379
    timeout 300
    tcp-keepalive 60
    
    # 内存配置
    maxmemory 2gb
    maxmemory-policy allkeys-lru
    
    # 持久化配置
    save 900 1
    save 300 10
    save 60 10000
    
    appendonly yes
    appendfsync everysec
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    
    # 日志配置
    loglevel notice
    
    # 客户端配置
    maxclients 10000 