apiVersion: v1
kind: Secret
metadata:
  name: miniodb-secrets
  namespace: miniodb-system
  labels:
    app.kubernetes.io/name: miniodb
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Redis 密码 (base64编码: redis123)
  redis-password: cmVkaXMxMjM=
  
  # JWT 密钥 (base64编码: your-super-secret-jwt-key-change-in-production)
  jwt-secret: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
  
  # MinIO 主存储凭证
  # minioadmin (base64编码)
  minio-access-key: bWluaW9hZG1pbg==
  # minioadmin123 (base64编码)
  minio-secret-key: bWluaW9hZG1pbjEyMw==
  
  # MinIO 备份存储凭证
  # minioadmin (base64编码)
  minio-backup-access-key: bWluaW9hZG1pbg==
  # minioadmin123 (base64编码)
  minio-backup-secret-key: bWluaW9hZG1pbjEyMw==

---
# TLS证书 Secret (可选，用于HTTPS)
apiVersion: v1
kind: Secret
metadata:
  name: miniodb-tls
  namespace: miniodb-system
  labels:
    app.kubernetes.io/name: miniodb
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  # 注意：这里是示例，生产环境请使用真实的证书
  # 生成方式：
  # openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt
  # cat tls.crt | base64 -w 0
  # cat tls.key | base64 -w 0
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi4uLgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t 