# Redis 角色默认配置
---

# Redis 版本配置
redis:
  version: "7-alpine"
  
  # 基本网络配置
  bind_address: "0.0.0.0"
  port: 6379
  timeout: 300
  tcp_keepalive: 60
  tcp_backlog: 511
  
  # 安全配置
  # password: "your_redis_password"  # 取消注释并设置密码
  
  # 数据库配置
  databases: 16
  
  # 日志配置
  log_level: "notice"
  log_path: "/opt/miniodb/logs/redis"
  log_max_size: "10m"
  log_max_file: "3"
  syslog_enabled: "no"
  
  # 数据路径配置
  data_path: "/opt/miniodb/data/redis"
  config_path: "/opt/miniodb/config/redis"
  
  # 持久化配置 - RDB
  rdb_enabled: true
  rdb_save_rules: "900 1 300 10 60 10000"
  rdb_filename: "dump.rdb"
  rdb_compression: "yes"
  rdb_checksum: "yes"
  stop_writes_on_bgsave_error: "yes"
  rdb_save_incremental_fsync: "yes"
  
  # 持久化配置 - AOF
  aof_enabled: false
  aof_filename: "appendonly.aof"
  aof_fsync: "everysec"
  aof_no_fsync_on_rewrite: "no"
  aof_rewrite_percentage: 100
  aof_rewrite_min_size: "64mb"
  aof_load_truncated: "yes"
  aof_rewrite_incremental_fsync: "yes"
  
  # 内存配置
  # maxmemory: "1gb"
  # maxmemory_policy: "allkeys-lru"
  # maxmemory_samples: 5
  
  # 客户端配置
  maxclients: 10000
  client_output_buffer_limit_normal: "0 0 0"
  client_output_buffer_limit_replica: "256mb 64mb 60"
  client_output_buffer_limit_pubsub: "32mb 8mb 60"
  client_query_buffer_limit: "1gb"
  
  # 协议配置
  proto_max_bulk_len: "512mb"
  
  # 性能配置
  hz: 10
  dynamic_hz: "yes"
  activerehashing: "yes"
  jemalloc_bg_thread: "yes"
  
  # 慢查询配置
  slowlog_log_slower_than: 10000
  slowlog_max_len: 128
  
  # 延迟监控
  latency_monitor_threshold: 0
  
  # 数据结构配置
  hash_max_ziplist_entries: 512
  hash_max_ziplist_value: 64
  list_max_ziplist_size: -2
  list_compress_depth: 0
  set_max_intset_entries: 512
  zset_max_ziplist_entries: 128
  zset_max_ziplist_value: 64
  hll_sparse_max_bytes: 3000
  stream_node_max_bytes: 4096
  stream_node_max_entries: 100
  
  # 健康检查配置
  health_check:
    interval: 30
    timeout: 10
    retries: 3
    start_period: 10
  
  # 安全命令重命名
  # rename_commands:
  #   FLUSHDB: "FLUSHDB_RENAMED"
  #   FLUSHALL: "FLUSHALL_RENAMED"
  #   CONFIG: "CONFIG_RENAMED"
  #   SHUTDOWN: "SHUTDOWN_RENAMED"
  
  # 事件通知
  # notify_keyspace_events: "Ex"
  
  # 模块加载
  # modules:
  #   - "/path/to/module.so"
  
  # 自定义配置
  # custom_config:
  #   - "# Custom configuration"
  #   - "some-custom-option value"

# 系统配置
system:
  # Redis 用户和组
  user: "miniodb"
  group: "miniodb"
  uid: 1000
  gid: 1000
  
  # 系统依赖
  dependencies:
    - curl
    - wget
    - docker.io
    - docker-compose
  
  # 防火墙端口配置
  firewall_ports:
    - "{{ redis.port }}/tcp"

# Docker 配置
docker:
  # 重启策略
  restart_policy: "unless-stopped"
  
  # 网络配置
  network_name: "miniodb-network"
  
  # 资源限制
  resources:
    memory: "512m"
    cpus: "0.5"
    reserved_memory: "256m"
    reserved_cpus: "0.25"
  
  # 日志驱动配置
  logging:
    driver: "json-file"

# 监控配置
monitoring:
  # 启用监控
  enabled: true
  
  # 健康检查端点
  health_endpoints:
    - "http://localhost:{{ redis.port }}"
  
  # 指标收集
  metrics:
    enabled: false
    port: 9121
    path: "/metrics"

# 备份配置
backup:
  # 自动备份
  auto_backup: false
  
  # 备份调度
  schedule: "0 3 * * *"  # 每天凌晨3点
  
  # 备份保留策略
  retention:
    days: 7
    
  # 备份存储位置
  storage_path: "/opt/miniodb/backups/redis" 