apiVersion: v1
kind: Service
metadata:
  name: miniodb-service
  namespace: miniodb-system
  labels:
    app.kubernetes.io/name: miniodb
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: miniodb-system
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: grpc
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: rest
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app.kubernetes.io/name: miniodb

---
# MinIODB External Service (用于外部访问)
apiVersion: v1
kind: Service
metadata:
  name: miniodb-external
  namespace: miniodb-system
  labels:
    app.kubernetes.io/name: miniodb
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: miniodb-system
spec:
  type: NodePort  # 或 LoadBalancer，根据集群情况选择
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080  # 外部gRPC访问端口
    protocol: TCP
    name: grpc
  - port: 8081
    targetPort: 8081
    nodePort: 30081  # 外部REST访问端口
    protocol: TCP
    name: rest
  - port: 9090
    targetPort: 9090
    nodePort: 30090  # 外部监控访问端口
    protocol: TCP
    name: metrics
  selector:
    app.kubernetes.io/name: miniodb

---
# MinIODB Headless Service (用于服务发现)
apiVersion: v1
kind: Service
metadata:
  name: miniodb-headless
  namespace: miniodb-system
  labels:
    app.kubernetes.io/name: miniodb
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: miniodb-system
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: grpc
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: rest
  selector:
    app.kubernetes.io/name: miniodb 